/**
 * Centralised DOM ID and class name constants for the editor.
 * All IDs are prefixed "ts-" to avoid collisions when embedded in a larger page.
 * No CSS modules required — these are plain strings used by both editorDom and uiController.
 */

export const EditorIds = {
  editorParent:              'ts-editor-parent',
  canvasParent:              'ts-canvas-parent',
  importToolbar:             'ts-import-toolbar',
  propertiesWindowParent:    'ts-properties-window-parent',
  propertiesWindow:          'ts-properties-window',
  propertiesWindowHeader:    'ts-properties-window-header',
  propertiesWindowHeaderText:'ts-properties-window-header-text',
  topCenterParentFlexboxParent:           'ts-top-center-flexbox-parent',
  bottomCenterFlexboxParent: 'ts-bottom-center-flexbox-parent',
  objectToolbar:             'ts-object-toolbar',
  objectSelectButton:        'ts-object-select-button',
  objectMoveButton:          'ts-object-move-button',
  objectRotateButton:        'ts-object-rotate-button',
  objectScaleButton:         'ts-object-scale-button',
  previewBackButton:         'ts-preview-back-button',
  playerPreviewParent:       'ts-player-preview-parent',
  vfxSelection:              'ts-vfx-selection',
  vfxSelectionBox:           'ts-vfx-selection-box',
  vfxBasicButton:            'ts-vfx-basic-button',
  vfxDustButton:             'ts-vfx-dust-button',
  vfxSnowButton:             'ts-vfx-snow-button',
  vfxRainButton:             'ts-vfx-rain-button',
  vfxFishButton:             'ts-vfx-fish-button',
  savingText:                'ts-saving-text',
  savedText:                 'ts-saved-text',
  topBarUI:               'ts-top-bar-ui',
  bottomBarUI:               'ts-bottom-bar-ui',
  previewButton:             'ts-preview-button',
  liveSiteButton:            'ts-live-site-button',
  saveButton:                'ts-save-button',
  colorPickerParent:         'ts-color-picker-parent',
  colorPicker:               'ts-color-picker',
  textInputPopupParent:      'ts-text-input-popup-parent',
  textInputPopupForm:        'ts-text-input-popup-form',
  textInputPopupInput:       'ts-text-input-popup-input',
  resetScenePopupParent:     'ts-reset-scene-popup-parent',
  resetSceneYesButton:       'ts-reset-scene-yes-button',
  resetSceneNoButton:        'ts-reset-scene-no-button',
  pathConfirmPopupParent:    'ts-path-confirm-popup-parent',
  pathConfirmPopupLabel:     'ts-path-confirm-popup-label',
  pathConfirmPathInput:      'ts-path-confirm-path-input',
  pathConfirmInput:          'ts-path-confirm-input',
  pathConfirmCancelButton:   'ts-path-confirm-cancel-button',
  savePopupParent:           'ts-save-popup-parent',
  savePopupTextarea:         'ts-save-popup-textarea',
  savePopupDownloadButton:   'ts-save-popup-download-button',
  savePopupBackButton:       'ts-save-popup-back-button',
  loadButton:                'ts-load-button',
  loadPopupParent:           'ts-load-popup-parent',
  loadPopupTextarea:         'ts-load-popup-textarea',
  loadPopupFileInput:        'ts-load-popup-file-input',
  loadPopupLoadButton:       'ts-load-popup-load-button',
  loadPopupBackButton:       'ts-load-popup-back-button',
  addTextButton:             'ts-add-text-button',
  add2DPageButton:           'ts-add-2d-page-button',
  addImageButton:            'ts-add-image-button',
  addVideoButton:            'ts-add-video-button',
  addModelButton:            'ts-add-model-button',
  addLightButton:            'ts-add-light-button',
  addMusicButton:            'ts-add-music-button',
  addVFXButton:              'ts-add-vfx-button',
  sceneSettingsButton:       'ts-scene-settings-button',
  projectViewContainer:      'ts-project-view-container',
  projectViewToggle:         'ts-project-view-toggle',
  projectViewPanel:          'ts-project-view-panel',
  projectViewTree:           'ts-project-view-tree',
};

export const EditorClasses = {
  firstUIDepth:          'ts-z1',
  secondUIDepth:         'ts-z2',
  thirdUIDepth:          'ts-z3',
  fourthUIDepth:         'ts-z9',
  fifthUIDepth:          'ts-z10',
  tooltipButton:         'ts-tooltip-btn',
  tooltip:               'ts-tooltip',
  tooltiptextBottom:     'ts-tooltip-bottom',
  tooltiptextLeft:       'ts-tooltip-left',
  modalUIParent:         'ts-modal-parent',
  modalUI:               'ts-modal-ui',
  modalUIVerticalLayout: 'ts-modal-vert',
  clickableUI:           'ts-clickable',
  orbitControlsGizmo:    'ts-orbit-gizmo',
  propertyRow:           'ts-property-row',
  sliderParent:          'ts-slider-parent',
  sliderNumber:          'ts-slider-number',
  slider:                'ts-slider',
};
